### ISSUE TITLE
Large numbers of flips have to be simulated individually

### ISSUE THREAD

**Issue by KingSupernova31** [fbatista/mtg-coin-flipper#1]
It looks like this is individually simulating every flip, and as a result it starts to slow down at around 10^7 flips. While this doesn't really impact its usefulness in real-world situations, I believe this could be avoided by instead calculating the appropriate probability distribution over all possible totals and just sampling from it once.

**Comment by fbatista** [comment]
That's correct, however, in order to have the verbose output, i don't think
we can do something like that.

**Comment by KingSupernova31** [comment]
Ah, good point, I didn't think about that. However verbose mode already runs into its own problems with smaller numbers of flips, since adding so much text to the DOM starts lagging the page far more than just the flip simulations. With verbose mode enabled, the page starts slowing down for me at only 10^5 flips. You could maybe have a cutoff for verbose mode at 10^4 flips and switch to non-verbose for anything above that.
